{{- if .Values.postgresql.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ish-monitoring-postgresqldb-exporter.fullname" . }}
  labels:
    app: {{ template "ish-monitoring-postgresqldb-exporter.name" . }}
    chart: {{ template "ish-monitoring-postgresqldb-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgresql_password: {{ .Values.postgresql.password | b64enc }}
{{- end -}}
