version: '3'

volumes:
  postgresql:
  postgresql_data:

networks:
  postgresql-prom-exporter:

services:
  postgresqlserver:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=YourStrong!Passw0rd
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgresql-prom-exporter

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - postgresql-prom-exporter

  postgresql-exporter:
    build:
      context: .
    depends_on:
      - postgresqlserver
    ports:
      - "8000:8000"
    environment:
      - POSTGRESQL_SSL=0
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_HOST=postgresqlserver
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=YourStrong!Passw0rd
      - FLASK_CONFIG=config.DevelopmentConfig
      - COLLECT_METRICS_INTERVAL_SEC=15
    networks:
      - postgresql-prom-exporter
